const data ={
  "one":{
    "two":[
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"

      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "four":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "Three":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ]
  },
  "one1":{
    "two":[
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "four":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "Three":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ]
  }
}

export {
  data
}
