const Userdata ={
  "0":{
    "2":[
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"

      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "3":[
      {
        "name":"蚂蚁3",
        "title":"人类"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "4":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ]
  },
  "1":{
    "4":[
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "5":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ],
    "6":[
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      },
      {
        "name":"蚂蚁3",
        "title":"人类",
        "address":"Ren"
      }
    ]
  }
}

export {
  Userdata
}
